version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - host=mysql
      - username=root
      - password=example
      - database=mydb
      - port=3306
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
